### ISSUE TITLE
Save, open and other buttons missing

### ISSUE THREAD

**Issue by hkmaly** [maxistar/TextPad#4] opened 2015-10-26 15:50 UTC
On screenshot, there are buttons like new, open, save and settings. I don't see them when I start the editor, with or without keyboard active. Tried lot of things to activate them but no success. I would consider it pretty serious bug for editor.

I suppose you would need some additional information but I'm not sure what informations. The phone is Asus ZenFone 2 ZE551ML, the android 5.0 (possibly 5.0.35.1), kernel 3.10.20-x86_64 ...

**Comment by maxistar** [comment] 2015-10-27 05:57
Thanks for report!

so far I was not able to reproduce the issue, but you are second person who reported this. The bug appears only on some devices after update to Android 5 or Android 5.1. Think it is something related with display ppi, could you also send me your sreenshot? (on android 5 you can click same time power and volume down buttons to create screenshot.)
I will try to fix.

Best regards,
Max

**Comment by hkmaly** [comment] 2015-11-10 18:13
While I did updated once, I'm sure it has Android 5 before as well.

Whoa, usefull. Ok, adding screenshot - actually two, one with keyboard and one without. Don't think it you will see anything on it but better than nothing.

![screenshot_2015-11-10-19-00-10](https://cloud.githubusercontent.com/assets/4201080/11071039/12b061ba-87df-11e5-908e-9101fb9bd7ac.jpg)
![screenshot_2015-11-10-19-09-06](https://cloud.githubusercontent.com/assets/4201080/11071040/12b49474-87df-11e5-9e20-36593d711f3f.jpg)

Sorry it took so long.
   Honza

**Comment by maxistar** [comment] 2021-02-28 20:19
the issue is fixed in the version 1.12.0

**Closed by maxistar** 2021-02-28 20:19 UTC
